AWSTemplateFormatVersion: 2010-09-09
Description: An instance for ad-hoc work

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/cloud9/amis/amazonlinux-2-x86_64'

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub Security group for ${AWS::StackName}
      GroupName: !Sub ${AWS::StackName}-sg
      VpcId: !ImportValue infra-vpc-VpcId
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-sg' }

  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /
      RoleName: !Sub ${AWS::StackName}-role
      Policies:
        - PolicyName: ExtraAccess
          PolicyDocument: {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Sid": "EKSAccess",
                      "Effect": "Allow",
                      "Action": [
                          "eks:DescribeCluster"
                      ],
                      "Resource": "*"
                  }
              ]
          }

  RoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role
      InstanceProfileName: !Sub '${AWS::StackName}-profile'

  LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-template
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              Encrypted: true
              VolumeSize: 100
              VolumeType: gp3
        IamInstanceProfile:
          Arn: !GetAtt RoleProfile.Arn
        ImageId: !Ref LatestAmiId
        InstanceType: m5.large
        KeyName: sjakthol
        SecurityGroupIds:
          - !Ref SecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: Name, Value: !Sub '${AWS::StackName}' }
          - ResourceType: volume
            Tags:
              - { Key: Name, Value: !Sub '${AWS::StackName}-volume' }
        UserData:
          Fn::Base64: |
            #!/bin/bash
            set -o xtrace
            yum install -y amazon-ssm-agent
            systemctl start amazon-ssm-agent

            # Install some tools
            yum install -y tmux htop iftop iotop parallel

            # Upgrade pip
            python3 -m pip install --upgrade pip

            # Install some Python dev tools
            python3 -m pip install --user --upgrade poetry tox

            # Install AWS CLI v2
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
              && unzip -q awscliv2.zip \
              && ./aws/install \
              && rm -rf ./aws awscliv2.zip

            # Install Docker buildx
            wget https://github.com/docker/buildx/releases/download/v0.6.0/buildx-v0.6.0.linux-amd64
            chmod a+x buildx-v0.6.0.linux-amd64
            mkdir -p /usr/local/lib/docker/cli-plugins
            mv buildx-v0.6.0.linux-amd64 /usr/local/lib/docker/cli-plugins/docker-buildx

            # Install kubectl
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/

  Instance:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '0'
      MaxSize: '1'
      DesiredCapacity: '1'
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandBaseCapacity: 0 # set to 1 to get on-demand
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: capacity-optimized
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref LaunchTemplate
            Version: !GetAtt LaunchTemplate.LatestVersionNumber
          Overrides:
            - InstanceType: m5.xlarge
            - InstanceType: r5.xlarge
            - InstanceType: c5.xlarge
      VPCZoneIdentifier:
        - !ImportValue infra-vpc-sn-public-a
        - !ImportValue infra-vpc-sn-public-b
