AWSTemplateFormatVersion: 2010-09-09
Description: An instance for ad-hoc work

Parameters:
  SSHKeyName:
    Description: Name of an existing EC2 SSH key to give the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: sjakthol

  SSHInboundCidr:
    Description: The CIDR from which SSH access should be allowed from
    Type: String
    Default: '0.0.0.0/0'
    AllowedPattern : "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription : 'must be a valid CIDR range of the form x.x.x.x/x.'

Mappings:
  RegionMap:
    eu-west-1:
      AmiId: ami-0bdb1d6c15a40392c

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow SSH access to host
      GroupName: !Sub ${AWS::StackName}-sg
      VpcId: !ImportValue infra-vpc-VpcId
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: !Ref SSHInboundCidr, Description: "SSH Access" }
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-sg' }

  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-role
      Policies:
      - PolicyName: Ec2InstanceRole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: PlaceholderPolicy
            Effect: Allow
            Action:
              - ec2:DescribeInsances
            Resource: '*'

  RoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role
      InstanceProfileName: !Sub '${AWS::StackName}-profile'

  LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-template
      LaunchTemplateData:
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: Name, Value: !Sub '${AWS::StackName}' }
          - ResourceType: volume
            Tags:
              - { Key: Name, Value: !Sub '${AWS::StackName}-volume' }
        IamInstanceProfile:
          Arn: !GetAtt RoleProfile.Arn
        SecurityGroupIds:
          - !Ref SecurityGroup
        EbsOptimized: true
        KeyName: !Ref SSHKeyName
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
        ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AmiId]
        InstanceType: m5.large

  Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      SubnetId: !ImportValue infra-vpc-sn-public-a
