AWSTemplateFormatVersion: 2010-09-09
Description: NAT Gateway for infra VPC

Parameters:
  HighlyAvailable:
    Type: String
    Description: Whether to create a HA setup (regional NATGW that can expand to all AZs) or non-HA setup (regional NATGW with AZ-a only)
    AllowedValues:
      - true
      - false
    Default: false

Conditions:
  IsSingleZone: !Equals [!Ref HighlyAvailable, false]

Resources:
  NatAEIP:
    Type: AWS::EC2::EIP
    Condition: IsSingleZone
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AvailabilityMode: regional
      AvailabilityZoneAddresses:
        Fn::If:
          - IsSingleZone
          -
            - AllocationIds:
                - !GetAtt [NatAEIP, AllocationId]
              AvailabilityZone: !Sub ${AWS::Region}a
          - !Ref AWS::NoValue
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-natgateway' }
      VpcId:
        Fn::ImportValue: infra-vpc-VpcId

  NatARoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: infra-vpc-NatARouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  NatBRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: infra-vpc-NatBRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
