AWSTemplateFormatVersion: 2010-09-09
Description: IAM Roles for AWS Services

Resources:

  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-ApiGatewayLoggingRole
      Policies:
      - PolicyName: CloudWatchLogsAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: GlobalAPIAccess
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - logs:GetLogEvents
            - logs:FilterLogEvents
            Resource: '*'

  SageMakerDefaultExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-SageMakerDefaultExecutionRole
      Policies:
      - PolicyName: SageMakerExecutionRoleAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: GlobalAPIAccess
            Effect: Allow
            Action:
            # - sagemaker:*
            - ecr:GetAuthorizationToken
            - cloudwatch:PutMetricData
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - logs:GetLogEvents
            Resource: '*'
          - Sid: S3BucketLevelAccess
            Effect: Allow
            Action:
            - s3:ListBucket
            Resource: arn:aws:s3:::*sagemaker*
          - Sid: S3ObjectLevelAccess
            Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            Resource: arn:aws:s3:::*sagemaker*/*

Outputs:
  ApiGatewayLoggingRole:
    Description: The ARN of the API Gateway logging role
    Value: !GetAtt ApiGatewayLoggingRole.Arn

  SageMakerDefaultExecutionRole:
    Description: The ARN of the SageMaker notebook instance execution role
    Value: !GetAtt SageMakerDefaultExecutionRole.Arn
