AWSTemplateFormatVersion: 2010-09-09
Description: Infra level S3 buckets for this account

Resources:
  BuildResourcesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${AWS::Region}-build-resources'
      Tags:
        - { Key: Name, Value: !Sub '${AWS::AccountId}-${AWS::Region}-build-resources' }

  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${AWS::Region}-logs'
      Tags:
        - { Key: Name, Value: !Sub '${AWS::AccountId}-${AWS::Region}-logs' }

Outputs:
  BuildResourcesBucket:
    Description: 'The name of the build resources bucket for this account'
    Value: !Ref BuildResourcesBucket
    Export:
      Name: 'infra-buckets-BuildResourcesBucket'

  LogBucket:
    Description: 'The name of the log bucket for this account'
    Value: !Ref LogBucket
    Export:
      Name: 'infra-buckets-LogBucket'
