AWSTemplateFormatVersion: 2010-09-09
Description: Infra level S3 buckets for this account

Resources:
  BuildResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-build-resources
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - { Key: Name, Value: !Sub "${AWS::AccountId}-${AWS::Region}-build-resources" }

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-logs
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Status: Enabled
            ExpirationInDays: 30
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - { Key: Name, Value: !Sub "${AWS::AccountId}-${AWS::Region}-logs" }

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action:
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${LogBucket}/*
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

          - Sid: AllowRedshiftLogging
            Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${LogBucket}
              - !Sub arn:aws:s3:::${LogBucket}/*
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

          - Sid: AllowAWSLogDelivery
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${LogBucket}
              - !Sub arn:aws:s3:::${LogBucket}/*
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

          - Sid: AllowAlbLogging
            Effect: Allow
            Principal:
              Service: logdelivery.elb.amazonaws.com
              AWS:
                - arn:aws:iam::127311923021:root # us-east-1
                - arn:aws:iam::033677994240:root # us-east-2
                - arn:aws:iam::027434742980:root # us-west-1
                - arn:aws:iam::797873946194:root # us-west-2
                - arn:aws:iam::098369216593:root # af-south-1
                - arn:aws:iam::985666609251:root # ca-central-1
                - arn:aws:iam::054676820928:root # eu-central-1
                - arn:aws:iam::156460612806:root # eu-west-1
                - arn:aws:iam::652711504416:root # eu-west-2
                - arn:aws:iam::635631232127:root # eu-south-1
                - arn:aws:iam::009996457667:root # eu-west-3
                - arn:aws:iam::897822967062:root # eu-north-1
                - arn:aws:iam::754344448648:root # ap-east-1
                - arn:aws:iam::582318560864:root # ap-northeast-1
                - arn:aws:iam::600734575887:root # ap-northeast-2
                - arn:aws:iam::383597477331:root # ap-northeast-3
                - arn:aws:iam::114774131450:root # ap-southeast-1
                - arn:aws:iam::783225319266:root # ap-southeast-2
                - arn:aws:iam::589379963580:root # ap-southeast-3
                - arn:aws:iam::718504428378:root # ap-south-1
                - arn:aws:iam::076674570225:root # me-south-1
                - arn:aws:iam::507241528517:root # sa-east-1
            Action:
              - s3:GetBucketAcl
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${LogBucket}
              - !Sub arn:aws:s3:::${LogBucket}/*AWSLogs/${AWS::AccountId}/*

Outputs:
  BuildResourcesBucket:
    Description: The name of the build resources bucket for this account
    Value: !Ref BuildResourcesBucket
    Export:
      Name: infra-buckets-BuildResourcesBucket

  LogBucket:
    Description: The name of the log bucket for this account
    Value: !Ref LogBucket
    Export:
      Name: infra-buckets-LogBucket
