AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Guardduty for the account

Parameters:
  Contact:
    Description: The email to send Guardduty alerts to
    Type: String
    Default: sjakthol@outlook.com # You might want to change this

Resources:
  Detector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-alerts'

  AlertTopicPermission:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudwatchPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertTopic
      Topics:
        - !Ref AlertTopic

  AlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref Contact
      TopicArn: !Ref AlertTopic

  AlertRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Send an SNS alert if Guardduty detects an anomaly
      EventPattern:
        source:
          - aws.guardduty
      State: ENABLED
      Targets:
        - Arn: !Ref AlertTopic
          Id: GuarddutyToSns
