AWSTemplateFormatVersion: 2010-09-09
Description: AWS SSO setup for an organization

Parameters:
  InstanceArn:
    Type: String

Resources:

  ## Permission Sets ##

  ReadOnlyAccess:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: Provides read-only access to AWS account
      Name: ReadOnlyAccess
      InlinePolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowAccessToCostData",
              "Effect": "Allow",
              "Action": [
                "ce:DescribeCostCategoryDefinition",
                "ce:DescribeNotificationSubscription",
                "ce:DescribeReport",
                "ce:GetAnomalies",
                "ce:GetAnomalyMonitors",
                "ce:GetAnomalySubscriptions",
                "ce:GetCostAndUsage",
                "ce:GetCostAndUsageWithResources",
                "ce:GetCostCategories",
                "ce:GetCostForecast",
                "ce:GetDimensionValues",
                "ce:GetPreferences",
                "ce:GetReservationCoverage",
                "ce:GetReservationPurchaseRecommendation",
                "ce:GetReservationUtilization",
                "ce:GetRightsizingRecommendation",
                "ce:GetSavingsPlansCoverage",
                "ce:GetSavingsPlansPurchaseRecommendation",
                "ce:GetSavingsPlansUtilization",
                "ce:GetSavingsPlansUtilizationDetails",
                "ce:GetTags",
                "ce:GetUsageForecast",
                "ce:ListCostCategoryDefinitions",
                "cur:DescribeReportDefinitions"
              ],
              "Resource": "*"
            }
          ]
        }
      InstanceArn: !Ref InstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/AWSCloudShellFullAccess
        - arn:aws:iam::aws:policy/AWSSupportAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      SessionDuration: PT8H
      Tags:
        - { Key: Name, Value: ReadOnlyAccess }

  AdministratorAccess:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: Provides full access to AWS account
      Name: AdministratorAccess
      InstanceArn: !Ref InstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      SessionDuration: PT8H
      Tags:
        - { Key: Name, Value: AdministratorAccess }
