AWSTemplateFormatVersion: 2010-09-09
Description: IAM User(s) for the account

Parameters:
  InitialPasswordSjakthol:
    Description: The initial password for sjakthol user
    Type: String
    MinLength: 12
    MaxLength: 255
    # This is not the droid you are looking for :)
    Default: ',>Vj*$1*Cc!)'

Resources:
  sjakthol:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - admin-users
        - all-users
        - read-only-users
        - power-users
      LoginProfile:
        Password: !Ref InitialPasswordSjakthol
        PasswordResetRequired: true
      UserName: sjakthol
