AWSTemplateFormatVersion: 2010-09-09
Description: Infra level S3 buckets for this account

Resources:
  BuildResourcesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub '${AWS::AccountId}-${AWS::Region}-build-resources'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - { Key: Name, Value: !Sub '${AWS::AccountId}-${AWS::Region}-build-resources' }

  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub '${AWS::AccountId}-${AWS::Region}-logs'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Status: Enabled
            ExpirationInDays: 30
      Tags:
        - { Key: Name, Value: !Sub '${AWS::AccountId}-${AWS::Region}-logs' }

Outputs:
  BuildResourcesBucket:
    Description: 'The name of the build resources bucket for this account'
    Value: !Ref BuildResourcesBucket
    Export:
      Name: 'infra-buckets-BuildResourcesBucket'

  LogBucket:
    Description: 'The name of the log bucket for this account'
    Value: !Ref LogBucket
    Export:
      Name: 'infra-buckets-LogBucket'
