AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation StackSets to deploy common infra to all accounts.

Parameters:
  OrganizationalUnit:
    Type: String
  PublicKeyMaterialSjakthol:
    Type: String

Resources:
  InfraBuckets:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Description: Deploy infra buckets to all member accounts.
      OperationPreferences:
        FailureToleranceCount: 12
        MaxConcurrentCount: 12
        RegionConcurrencyType: PARALLEL
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref OrganizationalUnit
          Regions:
            - eu-west-1
            - eu-north-1
      StackSetName: !Sub ${AWS::StackName}-infra-buckets
      Tags:
        - { Key: Deployment, Value: infra }
        - { Key: Name, Value: !Sub "${AWS::StackName}-infra-buckets" }
      TemplateURL: !Sub
        - https://${BuildResourcesBucket}.s3.${AWS::Region}.amazonaws.com/stacksets/infra-buckets.yaml
        - BuildResourcesBucket: !ImportValue infra-buckets-BuildResourcesBucket

  InfraEc2key:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Description: Deploy EC2 SSH keys to all member accounts.
      OperationPreferences:
        FailureToleranceCount: 12
        MaxConcurrentCount: 12
        RegionConcurrencyType: PARALLEL
      Parameters:
        - { ParameterKey: PublicKeyMaterialSjakthol, ParameterValue: !Ref PublicKeyMaterialSjakthol }
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref OrganizationalUnit
          Regions:
            - eu-west-1
            - eu-north-1
      StackSetName: !Sub ${AWS::StackName}-infra-ec2key
      Tags:
        - { Key: Deployment, Value: infra }
        - { Key: Name, Value: !Sub "${AWS::StackName}-infra-ec2key" }
      TemplateURL: !Sub
        - https://${BuildResourcesBucket}.s3.${AWS::Region}.amazonaws.com/stacksets/infra-ec2key.yaml
        - BuildResourcesBucket: !ImportValue infra-buckets-BuildResourcesBucket

  InfraVpc:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Description: Deploy VPC and networking infra to all member accounts.
      OperationPreferences:
        FailureToleranceCount: 12
        MaxConcurrentCount: 12
        RegionConcurrencyType: PARALLEL
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref OrganizationalUnit
          Regions:
            - eu-west-1
            - eu-north-1
      StackSetName: !Sub ${AWS::StackName}-infra-vpc
      Tags:
        - { Key: Deployment, Value: infra }
        - { Key: Name, Value: !Sub "${AWS::StackName}-infra-vpc" }
      TemplateURL: !Sub
        - https://${BuildResourcesBucket}.s3.${AWS::Region}.amazonaws.com/stacksets/infra-vpc.yaml
        - BuildResourcesBucket: !ImportValue infra-buckets-BuildResourcesBucket
